services:

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    env_file:
      - ./.env
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=notifier
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    ports:
      - "3306:${PORT}"

  bot:
    build: .
    container_name: telegram-bot
    ports:
      - "8000:${PORT_BOT}"
